name: fluttter_socket_log_plugin
description: A Flutter package which provides remote socket logging to see debug prints outside the app. This is especially useful for QA testers.
version: 1.1.4
homepage: https://github.com/SomeoneAndNoone/flutter_socket_log_plugin

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3
  network_info_plus: ^3.0.2
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
# generate protofiles if you need to update
#  protoc --dart_out=../lib/gen ./flutterblue.proto

flutter:

  plugin:
    platforms:
      android:
        package: com.khamidjon.fluttter_socket_log_plugin
        pluginClass: FluttterSocketLogPlugin
      ios:
        pluginClass: FluttterSocketLogPlugin
      macos:
        pluginClass: FluttterSocketLogPlugin
      windows:
        pluginClass: FluttterSocketLogPlugin

